= Awesome NetBox
:autor:       WOLfgang Schricker
:email:       time@wols.org
:lang:        en
:antora-rel:  2.1.1
// NO empty line before!

image:https://img.shields.io/badge/license-FDL%20v1.3-blue.svg[license, link=modules/ROOT/attachments/LICENSE.txt]
image:https://img.shields.io/github/tag/wols/awesome-netbox.svg[tag, link=https://github.com/wols/awesome-netbox/tags]
image:https://img.shields.io/github/issues/wols/awesome-netbox.svg[issues, link=https://github.com/wols/awesome-netbox/issues]
image:https://img.shields.io/github/stars/wols/awesome-netbox.svg?style=social&label=Star[star, link=https://github.com/wols/awesome-netbox/stargazers]

'''

== NetBox

[quote]
____
NetBox is an IP address management (IPAM) and data center infrastructure management (DCIM) tool.

link:https://github.com/netbox-community/netbox[, window=_blank]
____

== Awesome NetBox

[quote]
____
NetBox is and can be much, much more!
____

link:https://wols.github.io/awesome-netbox/[*Awesome NetBox*] should be *a collection of vivid HOWTO and ideas* for the use of NetBox...

...an ideal supplement to the link:https://netbox.readthedocs.io/[NetBox documentation, window=_blank].

=== Awesome NetBox is a Antora documentation component

image:https://img.shields.io/badge/%40antora%2Fcli-%5E{antora-rel}-blue[@antora/cli, link=https://www.npmjs.com/package/@antora/cli, window=_blank]

[quote]
.Antora
____
A [Antora] documentation component typically represents the documentation for a product, application, project, microservice, or training course.

link:https://antora.org/[The multi-repository documentation site generator for tech writers who writing in AsciiDoc., window=_blank]

____

== License

link:modules/ROOT/attachments/LICENSE.txt[GNU Free Documentation License 1.3]

// awesome-netbox/README.adoc
